[package]
name = "coffee_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "^0.1.57"
serde = { version = "1.0", features = ["derive"] }
git2 = "0.15.0"
log = "0.4.17"
env_logger = "0.9.3"
tokio = { version = "1.22.0", features = ["process"] }
