[package]
name = "coffee_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "^0.1.57"
coffee_lib = { path = "../coffee_lib" }
tokio = { version = "1", features = ["fs"] }
