[package]
name = "coffee_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.22.0", features = ["rt"] }
clightningrpc-common = "0.3.0-beta.3"
clightningrpc-plugin = "0.3.0-beta.7"
coffee_core = { path = "../coffee_core" }
serde_json = "1"
